name: announdo
description: Announdo see all your announcements in one place!
publish_to: 'none'
version: 3.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  firebase_analytics: ^9.1.2
  firebase_database: ^9.0.8
  connectivity_plus: ^2.2.1
  flutter_launcher_icons: ^0.10.0
  http: ^0.13.4
  otp: ^3.0.2
  shared_preferences: ^2.0.13
  intl: ^0.17.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/1024.png"
  adaptive_icon_background: "#204E4A"
  adaptive_icon_foreground: "assets/icon/1024.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/new_announdo.gif

  fonts:
    - family: Lato
      fonts:
        - asset: assets\fonts\Lato-Regular.ttf
    - family: Lato-bold
      fonts:
        - asset: assets\fonts\Lato-Bold.ttf